/**
 * Created by Administrator on 2014/10/11.
 */
angular.module('myApp.router',[
    'ngRoute'
]).config(['$routeProvider',function($routeProvider){
    $routeProvider
        .when('/',{
            templateUrl:'views/home.html',
            controller:'baseCtrl'
        })
        .when('/home',{
            templateUrl:'views/home.html',
            controller:'baseCtrl'
        })
        .when('/template',{
            templateUrl:'views/template.html',
            controller:'templateCtl'
        })
}])
